---
title: "Developing Slurm Simulator: Micro3 Cluster, small trace"
author: nikolays@buffalo.edu
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    toc_depth: 2
    mathjax: null
    css: doc.css
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd(path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/analysis"))
library(stringr)
#library(rjson)
library(dplyr)
library(tibble)
library(lubridate)

#detach("package:RSlurmSimTools", unload=TRUE)
#devtools::document(path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"))
#devtools::install_local(path=path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"), force=TRUE)
library(RSlurmSimTools)


library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(cowplot)
#library(DepthProc)
#reticulate::source_python(file.path(system.file("python", package = "RSlurmSimTools"),"hostlist.py"))
#library(gplots)
#library(parallel)
library(plotly)


read_sacct_out <- function(filename,nodes_desc=NULL,extract_node_list=FALSE){
    cat("Read: ",filename,"\n")
  
    if(grepl(".zst", filename, fixed=TRUE)){
      slurm_log <- data.table::fread(cmd=paste("zstdcat", filename),sep="|",header=TRUE)
    } else {
      slurm_log <- data.table::fread(filename,sep="|",header=TRUE)
    }
    
    #for(col in c("Submit","Eligible","Start","End","Elapsed","Timelimit",
    #             "Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        #cat(paste0(col,"S=",col,",\n"))
        #cat(paste0(col,"S,"))
    #}
    slurm_log <-  dplyr::rename(slurm_log,
        JobId=JobID,
        JobIdRaw=JobIDRaw,
        NodeCount=NNodes,
        SubmitS=Submit,
        EligibleS=Eligible,
        StartS=Start,
        EndS=End,
        ElapsedS=Elapsed,
        TimelimitS=Timelimit,
        ClusterS=Cluster,
        PartitionS=Partition,
        AccountS=Account,
        GroupS=Group,
        UserS=User,
        ExitCodeS=ExitCode,
        StateS=State,
        QOSS=QOS
    )
    #convert job names
    slurm_log$JobRecID <- as.integer(str_replace(slurm_log$JobName, "jobid_",""))
    if(sum(is.na(slurm_log$JobRecID)) > 0.5 * length(slurm_log$JobRecID )) {
      slurm_log$JobRecID <- as.integer(str_replace(slurm_log$JobName, "job_",""))
    }
    if(sum(is.na(slurm_log$JobRecID)) > 0.5 * length(slurm_log$JobRecID )) {
      warning("Can not extract job id from job name will use raw job id")
      slurm_log$JobRecID <- slurm_log$JobIdRaw
    }
    
    #convert to proper format
    for(col in c("Submit","Eligible","Start","End")){
        slurm_log[[col]] <- as.POSIXct(slurm_log[[paste0(col,"S")]],format = "%Y-%m-%dT%H:%M:%S")
    }
    
    #duration
    for(col in c("Elapsed","Timelimit")){
        slurm_log[,col] <- extract_slurm_period(slurm_log[[paste0(col,"S")]])
    }
    
    #factor
    for(col in c("Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        slurm_log[,col] <- factor(slurm_log[[paste0(col,"S")]])
    }
    
    #state
    slurm_log$StateS <- as.character(slurm_log$StateS)
    slurm_log$StateS[grepl("CANCELLED",slurm_log$StateS)] <- "CANCELLED"
    slurm_log$State <- as.factor(slurm_log$StateS)
    
    #extract node list
    if(extract_node_list==TRUE){
        #python.load(file.path(rutil_dir,"..","src","hostlist.py"))
        #slurm_log$NodeListFull <- python.call("expand_hostlists_to_str",slurm_log$NodeList)
        slurm_log$NodeListFull <- expand_hostlists_to_list(slurm_log$NodeList)
    }

    #convert memory
    slurm_log$ReqMem[slurm_log$ReqMem=="0n"] <- "0Mn"
    reqmem <- stringr::str_match_all(slurm_log$ReqMem, "([\\.0-9]+)([MG])([nc]?)")
    
    reqmem_size <- sapply(reqmem,function(r){
        as.integer(r[[2]])
    })
    reqmem_unit <- sapply(reqmem,function(r)r[[3]])
    reqmem_perwhat <- sapply(reqmem,function(r)r[[4]])
    #convert to MB
    reqmem_size[reqmem_unit=="G"] <- reqmem_size[reqmem_unit=="G"]*1024
    
    slurm_log$ReqMemSize <- reqmem_size
    slurm_log$ReqMemPerNode <- reqmem_perwhat=="n" || reqmem_perwhat==""
    
    slurm_log$ReqMem <- NULL
    
    #set proper NA
    #slurm_log$ReqGRES[slurm_log$ReqGRES==""] <- NA
    if(!is.null(nodes_desc)){
      nr <- max(sapply(nodes_desc,function(n){length(n$Nodes)}))
      
      nodes_mat <- sapply(nodes_desc,function(n){c(n$Nodes,rep(NA,nr-length(n$Nodes)))})
      
      #assing nodes
      nodes_types_used <- sapply(slurm_log$NodeListFull,function(nodes){
        apply(nodes_mat,2,function(v){length(intersect(v,nodes))})
      })
      
      slurm_log <- cbind(slurm_log,t(nodes_types_used))
    }
    
    slurm_log$SubmitTS <- as.integer(slurm_log$Submit)
    slurm_log$StartTS <- as.integer(slurm_log$Start)
    slurm_log$EndTS <- as.integer(slurm_log$End)
    
    
    slurm_log$WaitHours <- as.integer(slurm_log$Start-slurm_log$Submit)/3600.0
    slurm_log$WaitHours[slurm_log$WaitHours<0.0] <- slurm_log$WaitHours[slurm_log$WaitHours<0.0]+1
    
    slurm_log$WallHours <- as.integer(slurm_log$Elapsed)/3600.0
    slurm_log$NodeHours <- slurm_log$WallHours*slurm_log$NodeCount
    
    #shift 0 value for log scales
    slurm_log$WaitHours4log <- slurm_log$WaitHours
    slurm_log$WaitHours4log[slurm_log$WaitHours4log<1/60]<-1/60
    #shift 0 value for log scales
    slurm_log$WallHours4log <- slurm_log$WallHours
    slurm_log$WallHours4log[slurm_log$WallHours4log<1/60]<-1/60
    
    slurm_log <- dplyr::arrange(slurm_log,SubmitTS)%>%
        dplyr::select(-c(SubmitS,EligibleS,StartS,EndS,ElapsedS,TimelimitS,ClusterS,
                         PartitionS,AccountS,GroupS,UserS,ExitCodeS,StateS,QOSS))
    
    min_time <- min(min(slurm_log$SubmitTS, na.rm=TRUE),min(slurm_log$StartTS, na.rm=TRUE),min(slurm_log$EndTS, na.rm=TRUE), na.rm=TRUE)
    
    slurm_log$SubmitTime <- slurm_log$SubmitTS - min_time
    slurm_log$StartTime <- slurm_log$StartTS - min_time
    slurm_log$EndTime <- slurm_log$EndTS - min_time
    slurm_log$WallTime <- slurm_log$EndTime - slurm_log$StartTime
    slurm_log$WaitTime <- slurm_log$StartTime - slurm_log$SubmitTime
    
    slurm_log <- relocate(slurm_log, JobRecID, SubmitTime, StartTime, EndTime, WallTime, WaitTime, .before = "JobId")
    
    return(slurm_log)
}

read_sacct_out_multiple <- function(slurm_mode, results_root_dir, dtstart_list, run_id_list, sacct_out="slurm_acct.out") {
  result_list <- list()
  for(dtstart in dtstart_list) {
    for(run_id in run_id_list) {
      m_result_root_dir <- path.expand(file.path(results_root_dir, paste0("dtstart_", dtstart, "_", run_id)))
      m_sacct_out_filename <- file.path(m_result_root_dir, sacct_out)
      
      if(!dir.exists(m_result_root_dir)) {
          warning(sprintf("Directory %s does not exists!", m_result_root_dir))
          return(NULL);
      }
      if(!file.exists(m_sacct_out_filename)) {
          if (file.exists(paste0(m_sacct_out_filename,".zst"))) {
              m_sacct_out_filename <- paste0(m_sacct_out_filename,".zst")
          } else {
              warning(sprintf("File %s does not exists!", m_sacct_out_filename))
              return(NULL);
          }
      }
      m_sacct_out <- read_sacct_out(m_sacct_out_filename)
      m_sacct_out$slurm_mode <- slurm_mode
      m_sacct_out$dtstart <- dtstart
      m_sacct_out$run_id <- run_id
      
      m_sacct_out <- relocate(m_sacct_out,slurm_mode,dtstart,run_id, .before = "JobRecID")
      result_list[[length(result_list)+1]] <- m_sacct_out
      
    }
  }
  return(data.table::rbindlist(result_list))
}


read_events_csv <- function(filename,nodes_desc=NULL,extract_node_list=FALSE){
    cat("Read: ",filename,"\n")
  
    if(grepl(".zst", filename, fixed=TRUE)){
      events <- data.table::fread(cmd=paste("zstdcat", filename),sep=",",header=TRUE)
    } else {
      events <- data.table::fread(filename,sep=",",header=TRUE)
    }
    
    return(events)
}

read_events_multiple <- function(slurm_mode, results_root_dir, dtstart_list, run_id_list, events_csv="slurmctld_log.csv") {
  result_list <- list()
  for(dtstart in dtstart_list) {
    for(run_id in run_id_list) {
      m_result_root_dir <- path.expand(file.path(results_root_dir, paste0("dtstart_", dtstart, "_", run_id)))
      m_events_csv_filename <- file.path(m_result_root_dir, events_csv)
      
      if(!dir.exists(m_result_root_dir)) {
          warning(sprintf("Directory %s does not exists!", m_result_root_dir))
          return(NULL);
      }
      if(!file.exists(m_events_csv_filename)) {
          if (file.exists(paste0(m_events_csv_filename,".zst"))) {
              m_events_csv_filename <- paste0(m_events_csv_filename,".zst")
          } else {
              warning(sprintf("File %s does not exists!", m_events_csv_filename))
              return(NULL);
          }
      }
      m_events_csv <- read_events_csv(m_events_csv_filename)
      m_events_csv$slurm_mode <- slurm_mode
      m_events_csv$dtstart <- dtstart
      m_events_csv$run_id <- run_id
      
      m_events_csv <- relocate(m_events_csv,slurm_mode,dtstart,run_id, .before = "job_rec_id")
      result_list[[length(result_list)+1]] <- m_events_csv
      
    }
  }
  return(data.table::rbindlist(result_list))
}
```

```{r}
#JobName
# ../../../slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small/
sacct <- bind_rows(
  #read_sacct_out_multiple("b0_tarball", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/small__ref"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b1_351d", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b2_fbb2", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_2_fbb23b6cadcad237ffcc06d6cd87e035d138e279/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b3_b07f", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_3_b07f7071f32c0ddd10b468041abdc4c34ef9b7c2/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b4_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
#  read_sacct_out_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
#  read_sacct_out_multiple("b5_f588", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_5_146f125da6b5edad5f8723286d5bcd884a9b6b1c/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b6_af43", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_6_af43b09f8b5edc71028ecc02e03d68f81111c290/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b_Z2_f588", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee_2_f588c59c7a52c00c95f8c84c94e9122048c0acd0/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  read_sacct_out_multiple("s2302", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_23.02/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1),
  read_sacct_out_multiple("s2311", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_23.11rc/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1),
  #read_sacct_out_multiple("z2302s1", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3sim/bumblebee_23.02_sim_796898/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1),
  read_sacct_out_multiple("zZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1)
)
#sacct$rid <- sacct$run_id + sacct$dtstart*100
#sacct
#read_sacct_out(path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small/dtstart_58_1/slurm_acct.out"))
#sacct
```

b0_tarball - build from official tarball
b1_351d4  - build from git using tag corresponding to above tarball, increased time accuracy in logs
b2_f588c - feed jobs from slurmctrld
b3_f588c - reduced threads
b4_4c06 - front end mode (slightly different outcomes)

```{r}

events_time <- bind_rows(
  #read_events_multiple("b0_tarball", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/small__ref"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_events_multiple("b1_351d", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  read_events_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2, events_csv="slurmctld_log_time.csv")
)
events_time$t <- as.POSIXct(events_time$t)
events_time
#read_sacct_out_multiple("b0_tarball", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/small__ref"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_sacct_out_multiple("b1_351d", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
```


```{r}

events_proc <- bind_rows(
  #read_events_multiple("b0_tarball", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/small__ref"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_events_multiple("b1_351d", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  read_events_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2, events_csv="slurmctld_log_sinse_proc_created.csv")
)
#events_proc$t <- as.POSIXct(events_time$t)
events_proc


df <- events_proc %>% 
  filter(metric %in% c('slurm_start_time', 'process_create_real_time','sched','backfill','job_time_limits_testing')) %>%
  arrange(slurm_mode, dtstart, run_id,metric,t) %>%
  group_by(slurm_mode, dtstart, run_id,metric) %>%
  summarise(t=first(t),value=first(value),.groups="drop_last")

df$t[df$metric=="process_create_real_time"] <- as.POSIXct(df$value[df$metric=="process_create_real_time"], format="%Y-%m-%dT%H:%M:%OS")

df %>% select(-value) %>% spread(metric,t) %>% 
  mutate(sched=sched-process_create_real_time, backfill=backfill-process_create_real_time, job_time_limits_testing=job_time_limits_testing-process_create_real_time) %>%
   group_by(slurm_mode) %>%
  summarise(sched_avg=mean(sched),sched_sd=sd(sched),backfill_avg=mean(backfill),backfill_sd=sd(backfill),
            job_time_limits_testing_avg=mean(job_time_limits_testing),job_time_limits_testing_sd=sd(job_time_limits_testing))

```


```{r}

events_proc <- bind_rows(
  #read_events_multiple("b0_tarball", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/small__ref"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  #read_events_multiple("b1_351d", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2),
  read_events_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1:2, events_csv="slurmctld_log_sinse_proc_created.csv")#,
  #read_events_multiple("bZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/small"), c(58, 59, 68, 79, 89, 99, 105, 114, 126, 146), 1, events_csv="slurmctld_log_sinse_proc_created.csv"),
)
#events_proc$t <- as.POSIXct(events_time$t)
events_proc


df <- events_proc %>% 
  filter(metric %in% c('slurm_start_time', 'process_create_real_time','sched','backfill','job_time_limits_testing','slurmctld_background')) %>%
  arrange(slurm_mode, dtstart, run_id,metric,t) %>%
  group_by(slurm_mode, dtstart, run_id,metric) %>%
  summarise(t=first(t),value=first(value),.groups="drop_last")

df %>% select(-value) %>% spread(metric,t) %>% 
  group_by(slurm_mode) %>%
  summarise(sched_avg=mean(sched),sched_sd=sd(sched),
            backfill_avg=mean(backfill),backfill_sd=sd(backfill),
            job_time_limits_testing_avg=mean(job_time_limits_testing),job_time_limits_testing_sd=sd(job_time_limits_testing),
            slurmctld_background_avg=mean(slurmctld_background),slurmctld_background_sd=sd(slurmctld_background))

```

#
sched_avg
3.182659 secs	+- 0.01648027
backfill_avg
30.17454 secs +- 0.01301492	
job_time_limits_testing_sd
30.16486 secs +- 0.2260608


```{r}
jobs_summary <- sacct %>% group_by(slurm_mode,JobRecID) %>% summarise(
  SubmitTimeMean=mean(SubmitTime), SubmitTimeSD=sd(SubmitTime),
  StartTimeMean=mean(StartTime), StartTimeSD=sd(StartTime),
  WaitTimeMean=mean(WaitTime), WaitTimeSD=sd(WaitTime),
  WallTimeMean=mean(WallTime), WallTimeSD=sd(WallTime),
  .groups="drop_last"
) %>% arrange(JobRecID,slurm_mode)
jobs_summary
```

```{r fig.width=11}
plot_grid(
  ggplot(jobs_summary, aes(x=JobRecID,y=StartTimeMean, fill=slurm_mode)) + 
    geom_bar(stat="identity", position=position_dodge()) + 
    theme(legend.position="bottom"),
  ggplot(jobs_summary, aes(x=JobRecID,y=StartTimeSD, fill=slurm_mode)) + 
    geom_bar(stat="identity", position=position_dodge()) + 
    theme(legend.position="bottom"),
  ggplot(jobs_summary, aes(x=JobRecID,y=WallTimeMean, fill=slurm_mode)) + 
    geom_bar(stat="identity", position=position_dodge()) + 
    theme(legend.position="bottom"),
  ggplot(jobs_summary, aes(x=JobRecID,y=WallTimeSD, fill=slurm_mode)) + 
    geom_bar(stat="identity", position=position_dodge()) + 
    theme(legend.position="bottom"),
  ncol=1)
```


```{r fig.width=20}
cowplot::plot_grid(
ggplot(sacct, aes(x=factor(JobRecID),y=SubmitTime, color=slurm_mode)) + 
     geom_boxplot(position=position_dodge()) + 
     theme(legend.position="bottom"),
  ggplot(sacct, aes(x=factor(JobRecID),y=StartTime, color=slurm_mode)) + 
     geom_boxplot(position=position_dodge()) + 
     theme(legend.position="bottom"),
ggplot(sacct, aes(x=factor(JobRecID),y=WallTime, color=slurm_mode)) + 
     geom_boxplot(position=position_dodge()) + 
     theme(legend.position="bottom"), ncol=1
)
```

# Start Time Boxplot

```{r}
# 'max-width: 800px'
# "width: 100%; max-width: 800px;", width=1800

plot_ly(sacct, x = ~factor(JobRecID), y = ~StartTime, color = ~slurm_mode, type = "box") %>% 
  layout(boxmode = "group", legend = list(orientation = 'h', y=-0.2))
```

```{r}
# 'max-width: 800px'
# "width: 100%; max-width: 800px;", width=1800
# plotlyOutput(width = "1800px")/usr/lib/R/site-library/plotly/htmlwidgets/lib/plotlyjs/plotly-latest.min.js:
plot_ly(sacct, x = ~factor(JobRecID), y = ~WallTime, color = ~slurm_mode, type = "box") %>% 
  layout(boxmode = "group", legend = list(orientation = 'h', y=-0.2))
```

```{r}
# 'max-width: 800px'
# "width: 100%; max-width: 800px;", width=1800
# plotlyOutput(width = "1800px")/usr/lib/R/site-library/plotly/htmlwidgets/lib/plotlyjs/plotly-latest.min.js:
plot_ly(sacct, x = ~factor(JobRecID), y = ~WaitTime, color = ~slurm_mode, type = "box") %>% 
  layout(boxmode = "group", legend = list(orientation = 'h', y=-0.2))
```

```{r}
#plot_ly(sacct, x = ~factor(JobRecID), y = ~StartTime, color = ~slurm_mode, type = "box") %>% 
#  layout(boxmode = "group", legend = list(orientation = 'h', y=-0.2))

p <- ggplot(sacct, aes(x=factor(JobRecID), y=StartTime, color=slurm_mode, text=dtstart)) +
    geom_point(alpha = 0.3, position = position_dodge(width = 0.5))#+ 
#    stat_summary(fun.data = "mean_cl_boot", color = "black")# +
#    facet_wrap(~cut)

# WebGL is a lot more efficient at rendering lots of points
toWebGL(ggplotly(p, hoverinfo = 'text', text=paste0(sacct$slurm_mode,"\n",sacct$dtstart)))
```



```{r}
sacct %>% filter(dtstart==58 & slurm_mode %in% c('s2311', 'zZZ')) %>% arrange(JobRecID,slurm_mode, dtstart, run_id,StartTime)
```

```{r rows.print=20}
df1 <- sacct %>% filter(dtstart==58 & slurm_mode=='s2311' & run_id==1)
df1$job_rec_id <- df1$JobRecID-0.2

df2 <- sacct %>% filter(dtstart==58 & slurm_mode=='zZZ' & run_id==1)
df2$job_rec_id <- df2$JobRecID+0.2

print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(df1,df2) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,StartTime)

#df2 <- sacct %>% filter(dtstart==58 & slurm_mode=='bZZ' & run_id==2)
#df2$job_rec_id <- df$JobRecID+0.2



#data.table::rbindlist(list(df1,df2))
p <- ggplot(df) +
  geom_segment(mapping = aes(y=job_rec_id,yend=job_rec_id, x=SubmitTime,xend=StartTime),color="grey") +
  geom_segment(mapping = aes(y=job_rec_id,yend=job_rec_id, x=StartTime,xend=EndTime),color="red") +
  geom_point(mapping = aes(y=job_rec_id, x=SubmitTime),color="blue",shape=1) +
  geom_point(mapping = aes(y=job_rec_id, x=StartTime),color="red",shape=3) +
  geom_point(mapping = aes(y=job_rec_id, x=EndTime),color="green",shape=4) +
  geom_line(mapping = aes(y=job_rec_id,x=StartTime, linetype=id)) +
  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
ggplotly(p)
#p
```


```{r rows.print=20}
df1 <- sacct %>% filter(dtstart==58 & slurm_mode=='s2311' & run_id==1)
df1$job_rec_id <- df1$JobRecID-0.1

df2 <- sacct %>% filter(dtstart==58 & slurm_mode=='zZZ' & run_id==1)
df2$job_rec_id <- df2$JobRecID+0.1

print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(df1,df2) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,StartTime)

#df2 <- sacct %>% filter(dtstart==58 & slurm_mode=='bZZ' & run_id==2)
#df2$job_rec_id <- df$JobRecID+0.2



#data.table::rbindlist(list(df1,df2))
plot_ly(df) %>%
  add_segments(y=~job_rec_id,yend=~job_rec_id, x=~SubmitTime,xend=~StartTime,color=I("grey"), name="Wait Period") %>%
  add_segments(y=~job_rec_id,yend=~job_rec_id, x=~StartTime,xend=~EndTime,color=I("red"), name="Run Period") %>%
  add_markers(y=~job_rec_id, x=~SubmitTime, color=I("blue"), symbol=I('o'), name="Submit Time") %>%
  add_markers(y=~job_rec_id, x=~StartTime, color=I("red"), symbol=I('+'), name="Start Time") %>%
  add_markers(y=~job_rec_id, x=~EndTime, color=I("green"), symbol=I('x'), name="End Time") %>%
  add_paths(y=~job_rec_id,x=~StartTime, linetype=~id, legendgroup="Execution Order", color=I('black')) %>% 
  # ,legendgrouptitle=list(text="Execution Order"
  layout(
    yaxis = list(dtick = 1),
    xaxis = list(dtick = 10)
  )
#%>%
#  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
#  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
#ggplotly(p)
p
```

```{r}
dtstart <- 58
events <- bind_rows(
  #read_events_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), dtstart, 1),
  #read_events_multiple("bumblebee_1c_3f", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1c_3f4335f8f50378635795e8463bd5c137ec4734ff/small"), dtstart, 1),
  read_events_multiple("s2311", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_23.11rc/small"), dtstart, 1),
  #read_events_multiple("s2311", path.expand("~/slurm_sim_ws/slurm_model/micro3/results/bumblebee/small"), dtstart, 1),
  read_events_multiple("zZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/small"), dtstart, 1)
)

df1 <- events %>% filter(dtstart==dtstart & slurm_mode=='s2311' & run_id==1)
df1$job_rec_id2 <- df1$job_rec_id-0.2

df2 <- events %>% filter(dtstart==dtstart & slurm_mode=='zZZ' & run_id==1)
df2$job_rec_id2 <- df2$job_rec_id+0.2

#print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(df1,df2) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,t)
dfs <- filter(df, metric %in% c("submit_job","launch_job","job_epilog_complete")) %>% 
  dplyr::select(id,job_rec_id,job_rec_id2,metric,t) %>%
  group_by(id,job_rec_id,metric) %>%
  summarise(job_rec_id2=last(job_rec_id2),t=last(t))%>%
  spread(metric,t)


marker=list(size=10, line=list(width=2))
p <- plot_ly(df) %>%
    add_segments(data = filter(df, metric=='backfill'), y=I(1000),yend=I(1021), x=~t,xend=~t,color=I("grey"),alpha=I(0.5), linetype=~id, name="backfiller start") %>%
    add_segments(data = filter(df, metric=='sched'), y=I(1000),yend=I(1021), x=~t,xend=~t,color=I("#AED6F1"),alpha=I(0.5), linetype=~id, name="sched start") %>% #light blue
    add_segments(data = filter(df, metric=='job_time_limits_testing'), y=I(1000),yend=I(1021), x=~t,xend=~t,color=I("#AEF1D6"),alpha=I(0.5), linetype=~id, name="timelim check") %>% #light green
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~submit_job,xend=~launch_job,color=I("grey"), name="Wait Period") %>%
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~launch_job,xend=~job_epilog_complete,color=I("red"), name="Run Period") %>%
    add_markers(data = df %>% filter(metric=="submit_job"), y=~job_rec_id2, x=~t, color=I("grey"), symbol=I('o'), name="Submit Time",marker=marker) %>%
    add_markers(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2, x=~t, color=~value, colors=c("#0000FF","#00FF00"), symbol=I('cross'),marker=marker) %>% #I('+')
    add_markers(data = df %>% filter(metric=="job_epilog_complete"), y=~job_rec_id2, x=~t, color=I("red"), symbol=I('x'), name="End Time",marker=marker) %>%
    add_paths(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2,x=~t, linetype=~id, legendgroup="Execution Order", color=I('black')) %>% 
    layout(
      yaxis = list(dtick = 1),
      xaxis = list(dtick = 10)
    )
#htmlwidgets::saveWidget(p, "sample_sched_didnt_start_after_1004_ends.html")
  #

  # ,legendgrouptitle=list(text="Execution Order"

#%>%
#  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
#  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
#ggplotly(p)
p
```

```{r rows.print = 25}
df1 %>% filter(job_rec_id==1002)
```
```{r rows.print = 25}
df1 %>% filter(job_rec_id==1001)
```

```{r rows.print = 25}
df2 %>% filter(job_rec_id==1001)
```

```{r}
#sched
df1 %>% arrange(t) %>% filter(metric=="backfill")
```

```{r}
#df %>% filter(job_rec_id %in% c(1012,1007,1017) & metric=="nodes") %>% arrange(t) #%>% filter(metric=="backfill")
df2 %>% arrange(t) %>% filter(metric=="backfill")
3.317691-4.266231-.500000
```

	-54.779917	start	NA	b4fr_4c06 58 1
bZZ	58	1	NA	sched	-54.620774	start



```{r}
dtstart <- 79
events <- bind_rows(
  read_events_multiple("b4fr_4c06", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_4_4c06fd8cc8492dbfbe863a069e782ceb58376b9e_fixrep/small"), dtstart, 1),
  read_events_multiple("bZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/small"), dtstart, 1)
)

df1 <- events %>% filter(dtstart==dtstart & slurm_mode=='b4fr_4c06' & run_id==1)
df1$job_rec_id2 <- df1$job_rec_id-0.2

df2 <- events %>% filter(dtstart==dtstart & slurm_mode=='bZZ' & run_id==1)
df2$job_rec_id2 <- df2$job_rec_id+0.2

#print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(df1,df2) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,t)
dfs <- filter(df, metric %in% c("submit_job","launch_job","job_epilog_complete")) %>% 
  dplyr::select(id,job_rec_id,job_rec_id2,metric,t) %>%
  #group_by(id,job_rec_id,metric) %>%
  #summarise(n=n())%>% arrange(n)
  spread(metric,t)


marker=list(size=10, line=list(width=2))
p <- plot_ly(df) %>%
    add_segments(data = filter(df, metric=='backfill'), y=I(1000),yend=I(1021), x=~t,xend=~t,color=I("grey"),alpha=I(0.5), linetype=~id, name="backfiller start") %>%
    add_segments(data = filter(df, metric=='sched'), y=I(1000),yend=I(1021), x=~t,xend=~t,color=I("#AED6F1"),alpha=I(0.5), linetype=~id, name="sched start") %>% #light blue
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~submit_job,xend=~launch_job,color=I("grey"), name="Wait Period") %>%
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~launch_job,xend=~job_epilog_complete,color=I("red"), name="Run Period") %>%
    add_markers(data = df %>% filter(metric=="submit_job"), y=~job_rec_id2, x=~t, color=I("grey"), symbol=I('o'), name="Submit Time",marker=marker) %>%
    add_markers(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2, x=~t, color=~value, colors=c("#0000FF","#00FF00"), symbol=I('cross'),marker=marker) %>% #I('+')
    add_markers(data = df %>% filter(metric=="job_epilog_complete"), y=~job_rec_id2, x=~t, color=I("red"), symbol=I('x'), name="End Time",marker=marker) %>%
    add_paths(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2,x=~t, linetype=~id, legendgroup="Execution Order", color=I('black')) %>% 
    layout(
      yaxis = list(dtick = 1),
      xaxis = list(dtick = 10)
    )
#htmlwidgets::saveWidget(p, "sample_sched_didnt_start_after_1004_ends.html")
  #

  # ,legendgrouptitle=list(text="Execution Order"

#%>%
#  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
#  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
#ggplotly(p)
p
```



```{r}
df %>% arrange(t) #%>% filter(metric=="backfill")
```

```{r}
#read_events_csv("/home/nikolays/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/small/dtstart_58_1/slurmctld_log.csv")
#df1
#filter(df, metric %in% c("submit_job","launch_job","job_epilog_complete")) %>% 
#  select(id,job_rec_id,job_rec_id2,metric,t) %>%
#  #group_by(id,job_rec_id,metric) %>%
#  #summarise(n=n())%>% arrange(n)
#  spread(metric,t)

#sched                            109.492565                   start                           
#NA           backfill
filter(df, metric=='sched')
```


