#!/usr/bin/env bash
# script to make Slurm DEBs
build_opt="release"
if [ $# -ge 1 ]; then
    build_opt=$1
fi
cd
cd debuild
echo "Build config: ${build_opt}"
wget ${SLURM_TAR_GZ_SOURCE:=https://download.schedmd.com/slurm/slurm-18.08.4.tar.bz2}

if [[ "$build_opt" == "release" ]]; then
    mv slurm-20-02-3-1.tar.gz slurm-20-02-3_1.orig.tar.gz && \
    tar xzf slurm-20-02-3_1.orig.tar.gz && \
    mv slurm-slurm-20-02-3-1 slurm-20-02-3-1 && \
    cd slurm-20-02-3-1 && \
    dh_make -sy && \
    dpkg-source -b . && \
    dpkg-buildpackage

elif [[ "$build_opt" == "debug" ]]; then
    rpmbuild -ta slurm*.tar.bz2 -D '%_with_cflags CFLAGS="-g -O0" --enable-debug --disable-optimizations'
else
    echo "Unknown build configuration."
fi
# mkdir -p /DEB/x86_64
# cp -rf debuild /DEB
echo "DONE"
