#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

date

#$SCRIPT_DIR/start_sim_loc -w $SCRIPT_DIR/job_traces/small.events -n small
$SCRIPT_DIR/start_sim_loc -w $SCRIPT_DIR/job_traces/jobs500_shrinked.events -n jobs500_shrinked
#$SCRIPT_DIR/start_sim_loc -w $SCRIPT_DIR/job_traces/jobs500.events -n jobs500

date

echo Done
