---
title: "Developing Slurm Simulator: ubhpc"
author: nikolays@buffalo.edu
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    toc_depth: 2
    mathjax: null
    css: doc.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd(path.expand("~/slurm_sim_ws/slurm_model/ubhpc/analysis"))
library(stringr)
#library(rjson)
library(dplyr)
library(tibble)
library(lubridate)

#detach("package:RSlurmSimTools", unload=TRUE)
#devtools::document(path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"))
#devtools::install_local(path=path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"), force=TRUE)
library(RSlurmSimTools)


library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(cowplot)
library(DepthProc)
reticulate::source_python(file.path(system.file("python", package = "RSlurmSimTools"),"hostlist.py"))
library(gplots)
#library(parallel)
library(plotly)


read_sacct_out <- function(filename,nodes_desc=NULL,extract_node_list=FALSE){
    cat("Read: ",filename,"\n")
  
    if(grepl(".zst", filename, fixed=TRUE)){
      slurm_log <- data.table::fread(cmd=paste("zstdcat", filename),sep="|",header=TRUE)
    } else {
      slurm_log <- data.table::fread(filename,sep="|",header=TRUE)
    }
    
    #for(col in c("Submit","Eligible","Start","End","Elapsed","Timelimit",
    #             "Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        #cat(paste0(col,"S=",col,",\n"))
        #cat(paste0(col,"S,"))
    #}
    slurm_log <-  dplyr::rename(slurm_log,
        JobId=JobID,
        JobIdRaw=JobIDRaw,
        NodeCount=NNodes,
        SubmitS=Submit,
        EligibleS=Eligible,
        StartS=Start,
        EndS=End,
        ElapsedS=Elapsed,
        TimelimitS=Timelimit,
        ClusterS=Cluster,
        PartitionS=Partition,
        AccountS=Account,
        GroupS=Group,
        UserS=User,
        ExitCodeS=ExitCode,
        StateS=State,
        QOSS=QOS
    )
    #convert job names
    slurm_log$JobRecID <- as.integer(str_replace(slurm_log$JobName, "jobid_",""))
    if(sum(is.na(slurm_log$JobRecID)) > 0.5 * length(slurm_log$JobRecID )) {
      slurm_log$JobRecID <- as.integer(str_replace(slurm_log$JobName, "job_",""))
    }
    if(sum(is.na(slurm_log$JobRecID)) > 0.5 * length(slurm_log$JobRecID )) {
      warning("Can not extract job id from job name will use raw job id")
      slurm_log$JobRecID <- slurm_log$JobIdRaw
    }
    
    #convert to proper format
    for(col in c("Submit","Eligible","Start","End")){
        slurm_log[[col]] <- as.POSIXct(slurm_log[[paste0(col,"S")]],format = "%Y-%m-%dT%H:%M:%S")
    }
    
    #duration
    for(col in c("Elapsed","Timelimit")){
        slurm_log[,col] <- extract_slurm_period(slurm_log[[paste0(col,"S")]])
    }
    
    #factor
    for(col in c("Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        slurm_log[,col] <- factor(slurm_log[[paste0(col,"S")]])
    }
    
    #state
    slurm_log$StateS <- as.character(slurm_log$StateS)
    slurm_log$StateS[grepl("CANCELLED",slurm_log$StateS)] <- "CANCELLED"
    slurm_log$State <- as.factor(slurm_log$StateS)
    
    #extract node list
    if(extract_node_list==TRUE){
        #python.load(file.path(rutil_dir,"..","src","hostlist.py"))
        #slurm_log$NodeListFull <- python.call("expand_hostlists_to_str",slurm_log$NodeList)
        slurm_log$NodeListFull <- expand_hostlists_to_list(slurm_log$NodeList)
    }

    #convert memory
    slurm_log$ReqMem[slurm_log$ReqMem=="0n"] <- "0Mn"
    reqmem <- stringr::str_match_all(slurm_log$ReqMem, "([\\.0-9]+)([MG])([nc]?)")
    
    reqmem_size <- sapply(reqmem,function(r){
        as.integer(r[[2]])
    })
    reqmem_unit <- sapply(reqmem,function(r)r[[3]])
    reqmem_perwhat <- sapply(reqmem,function(r)r[[4]])
    #convert to MB
    reqmem_size[reqmem_unit=="G"] <- reqmem_size[reqmem_unit=="G"]*1024
    
    slurm_log$ReqMemSize <- reqmem_size
    slurm_log$ReqMemPerNode <- reqmem_perwhat=="n" | reqmem_perwhat==""
    
    slurm_log$ReqMem <- NULL
    
    #set proper NA
    #slurm_log$ReqGRES[slurm_log$ReqGRES==""] <- NA
    if(!is.null(nodes_desc)){
      nr <- max(sapply(nodes_desc,function(n){length(n$Nodes)}))
      
      nodes_mat <- sapply(nodes_desc,function(n){c(n$Nodes,rep(NA,nr-length(n$Nodes)))})
      
      #assing nodes
      nodes_types_used <- sapply(slurm_log$NodeListFull,function(nodes){
        apply(nodes_mat,2,function(v){length(intersect(v,nodes))})
      })
      
      slurm_log <- cbind(slurm_log,t(nodes_types_used))
    }
    
    slurm_log$SubmitTS <- as.integer(slurm_log$Submit)
    slurm_log$StartTS <- as.integer(slurm_log$Start)
    slurm_log$EndTS <- as.integer(slurm_log$End)
    
    
    slurm_log$WaitHours <- as.integer(slurm_log$Start-slurm_log$Submit)/3600.0
    
    slurm_log$WaitHours[is.na(slurm_log$WaitHours)] <- 0.0
    slurm_log$WaitHours[slurm_log$WaitHours<0.0] <- 0.0#slurm_log$WaitHours[slurm_log$WaitHours<0.0]+1
    
    slurm_log$WallHours <- as.integer(slurm_log$Elapsed)/3600.0
    slurm_log$NodeHours <- slurm_log$WallHours*slurm_log$NodeCount
    
    #shift 0 value for log scales
    slurm_log$WaitHours4log <- slurm_log$WaitHours
    slurm_log$WaitHours4log[slurm_log$WaitHours4log<1/60]<-1/60
    #shift 0 value for log scales
    slurm_log$WallHours4log <- slurm_log$WallHours
    slurm_log$WallHours4log[slurm_log$WallHours4log<1/60]<-1/60
    
    slurm_log <- dplyr::arrange(slurm_log,SubmitTS)%>%
        dplyr::select(-c(SubmitS,EligibleS,StartS,EndS,ElapsedS,TimelimitS,ClusterS,
                         PartitionS,AccountS,GroupS,UserS,ExitCodeS,StateS,QOSS))
    
    min_time <- min(min(slurm_log$SubmitTS, na.rm=TRUE),min(slurm_log$StartTS, na.rm=TRUE),min(slurm_log$EndTS, na.rm=TRUE), na.rm=TRUE)
    
    slurm_log$SubmitTime <- slurm_log$SubmitTS - min_time
    slurm_log$StartTime <- slurm_log$StartTS - min_time
    slurm_log$EndTime <- slurm_log$EndTS - min_time
    slurm_log$WallTime <- slurm_log$EndTime - slurm_log$StartTime
    slurm_log$WaitTime <- slurm_log$StartTime - slurm_log$SubmitTime
    
    slurm_log <- relocate(slurm_log, JobRecID, SubmitTime, StartTime, EndTime, WallTime, WaitTime, .before = "JobId")
    
    return(slurm_log)
}

read_sacct_out_multiple <- function(slurm_mode, results_root_dir, dtstart_list, run_id_list, sacct_out="slurm_acct.out") {
  result_list <- list()
  for(dtstart in dtstart_list) {
    for(run_id in run_id_list) {
      m_result_root_dir <- path.expand(file.path(results_root_dir, paste0("dtstart_", dtstart, "_", run_id)))
      m_sacct_out_filename <- file.path(m_result_root_dir, sacct_out)
      
      if(!dir.exists(m_result_root_dir)) {
          warning(sprintf("Directory %s does not exists!", m_result_root_dir))
          return(NULL);
      }
      if(!file.exists(m_sacct_out_filename)) {
          if (file.exists(paste0(m_sacct_out_filename,".zst"))) {
              m_sacct_out_filename <- paste0(m_sacct_out_filename,".zst")
          } else {
              warning(sprintf("File %s does not exists!", m_sacct_out_filename))
              return(NULL);
          }
      }
      m_sacct_out <- read_sacct_out(m_sacct_out_filename)
      m_sacct_out$slurm_mode <- slurm_mode
      m_sacct_out$dtstart <- dtstart
      m_sacct_out$run_id <- run_id
      
      m_sacct_out <- relocate(m_sacct_out,slurm_mode,dtstart,run_id, .before = "JobRecID")
      result_list[[length(result_list)+1]] <- m_sacct_out
      
    }
  }
  return(data.table::rbindlist(result_list))
}


read_events_csv <- function(filename,nodes_desc=NULL,extract_node_list=FALSE){
    cat("Read: ",filename,"\n")
  
    if(grepl(".zst", filename, fixed=TRUE)){
      events <- data.table::fread(cmd=paste("zstdcat", filename),sep=",",header=TRUE)
    } else {
      events <- data.table::fread(filename,sep=",",header=TRUE)
    }
    
    return(events)
}

read_events_multiple <- function(slurm_mode, results_root_dir, dtstart_list, run_id_list, events_csv="slurmctld_log.csv") {
  result_list <- list()
  for(dtstart in dtstart_list) {
    for(run_id in run_id_list) {
      m_result_root_dir <- path.expand(file.path(results_root_dir, paste0("dtstart_", dtstart, "_", run_id)))
      m_events_csv_filename <- file.path(m_result_root_dir, events_csv)
      
      if(!dir.exists(m_result_root_dir)) {
          warning(sprintf("Directory %s does not exists!", m_result_root_dir))
          return(NULL);
      }
      if(!file.exists(m_events_csv_filename)) {
          if (file.exists(paste0(m_events_csv_filename,".zst"))) {
              m_events_csv_filename <- paste0(m_events_csv_filename,".zst")
          } else {
              warning(sprintf("File %s does not exists!", m_events_csv_filename))
              return(NULL);
          }
      }
      m_events_csv <- read_events_csv(m_events_csv_filename)
      m_events_csv$slurm_mode <- slurm_mode
      m_events_csv$dtstart <- dtstart
      m_events_csv$run_id <- run_id
      
      m_events_csv <- relocate(m_events_csv,slurm_mode,dtstart,run_id, .before = "job_rec_id")
      result_list[[length(result_list)+1]] <- m_events_csv
      
    }
  }
  return(data.table::rbindlist(result_list))
}
```


```{r}
read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), 
                          c(37), 1)
```

```{r}
#JobName
# ../../../slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small/
sacct2 <- bind_rows(
  #read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), c(37, 49, 55, 71, 137, 232, 241, 261), 1), # i am not sure is it tarball
  read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), 
                          c(37, 49, 55, 71, 137, 232, 241, 261), 1), # i am not sure is it tarball
  read_sacct_out_multiple("um", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/mightybee_sim/workload"), 
                          c(71, 241, 261), 1),
  #read_sacct_out_multiple("wsa10", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/anvil_sim/anvil10/workload"), 
  #                        c(37, 55,79, 137,234, 241, 261), 1),
  read_sacct_out_multiple("va", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/anvil_sim/anvil4free/workload"),  # used to be "vsa4free"
                          c(37, 55, 137,232), 1),
  read_sacct_out_multiple("zZ", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/bumblebee/workload"), 
                          c(55, 137, 37, 232, 234, 49, 79), 1),
  
)
sacct2
```

```{r}
#for pics
# ../../../slurm_model_archive/micro3/bumblebee_1_351d4b6c2870284078531f082758f11116f0996d/small/
sacct2 <- bind_rows(
  #read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), c(37, 49, 55, 71, 137, 232, 241, 261), 1), # i am not sure is it tarball
  read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), 
                          c(37, 55, 137, 261), 1), # i am not sure is it tarball
  read_sacct_out_multiple("um", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/mightybee_sim/workload"), 
                          c(71, 241, 261), 1),
  #read_sacct_out_multiple("wsa10", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/anvil_sim/anvil10/workload"), 
  #                        c(37, 55,79, 137,234, 241, 261), 1),
  read_sacct_out_multiple("va", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/anvil_sim/anvil4free/workload"),  # used to be "vsa4free"
                          c(37, 55, 137,232), 1),
  read_sacct_out_multiple("zZ", path.expand("~/slurm_sim_ws/slurm_model/ubhpc/results/bumblebee/workload"), 
                          c(37, 55, 137,234), 1),
  
)
sacct2
```
```{r}
sacct2 %>% group_by(slurm_mode,dtstart,run_id) %>% summarise(n=n(),nna=sum(is.na(WaitTime)))
```

```{r}
sR <- read_sacct_out_multiple("tb", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/lakeeffect_tb/workload"), c(261), 1)
sZ <- read_sacct_out_multiple("ZZ", path.expand("~/slurm_sim_ws/slurm_model_archive/ubhpc/mightybee_sim/workload"), c(261), 1)
```

```{r}
inner_join(
  #sR %>% select(JobRecID,StartTime,SubmitTime,EndTime,WallTime,WaitTime),
  #sZ %>% select(JobRecID,StartTime,SubmitTime,EndTime,WallTime,WaitTime),
  sR %>% select(JobRecID,SubmitTime,WallTime),
  sZ %>% select(JobRecID,SubmitTime,WallTime),
  by="JobRecID",
  suffix = c("_R","_Z")) %>%
  filter(abs(WallTime_Z-WallTime_R)>3600)

```

```{r}
hist(sR$WallHours)
```

```{r}

hist(sZ$WallHours)
```

```{r}
259204/3600
84805	/3600
```

## Distance on Waittime

```{r fig.width=8, fig.height=6}
metrics_df <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
    mutate(id=sprintf("%s_%03d_%d", slurm_mode, dtstart, run_id)) %>% dplyr::select(-slurm_mode, -dtstart, -run_id) %>%
    dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
    spread(id, metric)

metrics_matrix <- metrics_df %>% dplyr::select(-job_rec_id) %>% as.matrix()
row.names(metrics_matrix) <- metrics_df$job_id

d <- dist(t(metrics_matrix))

#pdf(file = "ubhpc2.pdf", width = 12, height = 6)
heatmap.2(
    as.matrix(d)/3600,
    symm = T,trace = "none", scale = "none", 
    Rowv=FALSE, 
    col="bluered", key.title = NA, key.xlab="Distance, hour")
#dev.off()

#heatmap.2(
#    as.matrix(d)/1e5,
#    symm = T,trace = "none", scale = "none",
#    col="bluered", key.title = NA, key.xlab="Distance, hour")
```

NOTE:
TimeStart = 1641013200.0 produce early job_time_limits_testing happens
in 29 seconds for 146. TimeStart = 1641013200.1 already goes 30 sec.



## Multivariate Analysis

```{r fig.width=5, fig.height=5}
for(test in c("b1c", "b2_fb", "b4_4c", "bZZ")) {
  print(test)
  metrics_ref <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
    filter(slurm_mode=="b0_tb") %>% 
    unite(id,slurm_mode, dtstart, run_id) %>% 
    dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
    spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()
  metrics_test <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
      filter(slurm_mode==test) %>% 
      unite(id,slurm_mode, dtstart, run_id) %>% 
      dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
      spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()
  
  print(mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "Euclidean")))
  print(mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "LP")))
}

```

```{r fig.width=5, fig.height=5}
for(test in c("b0_tb", "b1c", "b2_fb", "b4_4c", "bR9")) {
  print(test)
  metrics_ref <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
    filter(slurm_mode=="bZZ") %>% 
    unite(id,slurm_mode, dtstart, run_id) %>% 
    dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
    spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()
  metrics_test <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
      filter(slurm_mode==test) %>% 
      unite(id,slurm_mode, dtstart, run_id) %>% 
      dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
      spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()
  
  print(mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "Euclidean")))
  print(mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "LP")))
}

```

```{r fig.width=5, fig.height=5}

metrics_ref <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
    filter(slurm_mode=="tb") %>% 
    unite(id,slurm_mode, dtstart, run_id) %>% 
    dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
    spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()
metrics_test <- sacct2 %>% arrange(slurm_mode, dtstart, run_id) %>%
    filter(slurm_mode=="sa") %>% 
    unite(id,slurm_mode, dtstart, run_id) %>% 
    dplyr::select(id, job_rec_id=JobRecID, metric=WaitTime) %>% 
    spread(id, metric) %>% dplyr::select(-job_rec_id) %>% as.matrix() %>% t()

mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "Euclidean"))
mWilcoxonTest(metrics_ref, metrics_test, depth_params = list(method = "LP"))
```

```{r}
dtstart <- 58
events <- bind_rows(
  read_events_multiple("b_TB", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_21.08.04_tarball/jobs500_shrinked__ref"), dtstart, 1),
  read_events_multiple("bZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/jobs500_shrinked"), dtstart, 1)
)

df1 <- events %>% filter(dtstart==dtstart & slurm_mode=='b_TB' & run_id==1)
df1$job_rec_id2 <- df1$job_rec_id-0.2

df2 <- events %>% filter(dtstart==dtstart & slurm_mode=='bZZ' & run_id==1)
df2$job_rec_id2 <- df2$job_rec_id+0.2

#print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(df1,df2) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,t)
# dfs <- filter(df, metric %in% c("submit_job","launch_job","job_epilog_complete")) %>% 
#   dplyr::select(id,job_rec_id,job_rec_id2,metric,t) %>%
#   #group_by(id,job_rec_id,metric) %>%
#   #summarise(n=n())%>% arrange(n)
#   spread(metric,t)


marker=list(size=10, line=list(width=2))
p <- plot_ly(df) %>%
    add_segments(data = filter(df, metric=='backfill'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("grey"),alpha=I(0.5), linetype=~id, name="backfiller start") %>%
    add_segments(data = filter(df, metric=='sched'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("#AED6F1"),alpha=I(0.5), linetype=~id, name="sched start") %>% #light blue
    add_segments(data = filter(df, metric=='job_time_limits_testing'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("#AEF1D6"),alpha=I(0.5), linetype=~id, name="timelim check") %>% #light green
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~submit_job,xend=~launch_job,color=I("grey"), name="Wait Period") %>%
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~launch_job,xend=~job_epilog_complete,color=I("red"), name="Run Period") %>%
    add_markers(data = df %>% filter(metric=="submit_job"), y=~job_rec_id2, x=~t, color=I("grey"), symbol=I('o'), name="Submit Time",marker=marker) %>%
    add_markers(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2, x=~t, color=~value, colors=c("#0000FF","#00FF00"), symbol=I('cross'),marker=marker) %>% #I('+')
    #add_markers(data = df %>% filter(metric=="job_epilog_complete"), y=~job_rec_id2, x=~t, color=I("red"), symbol=I('x'), name="End Time",marker=marker) %>%
    add_paths(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2,x=~t, linetype=~id, legendgroup="Execution Order", color=I('black')) %>% 
    layout(
      yaxis = list(dtick = 1),
      xaxis = list(dtick = 10)
    )
#htmlwidgets::saveWidget(p, "sample_sched_didnt_start_after_1004_ends.html")
  #

  # ,legendgrouptitle=list(text="Execution Order"

#%>%
#  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
#  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
#ggplotly(p)
p
```



```{r}
dtstart <- 58
events <- bind_rows(
  #read_events_multiple("bRR", path.expand("~/slurm_sim_ws/slurm_model_archive/micro3/bumblebee_1c_3f4335f8f50378635795e8463bd5c137ec4734ff/jobs500_shrinked"), dtstart, 1),
  read_events_multiple("bRR", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebeeR9/jobs500_shrinked"), dtstart, 1),
  read_events_multiple("bZZ", path.expand("~/slurm_sim_ws/slurm_model/micro3simdev/results/bumblebee/jobs500_shrinked"), dtstart, 1)
)

dfRR <- events %>% filter(dtstart==dtstart & slurm_mode=='bRR' & run_id==1)
dfRR$job_rec_id2 <- dfRR$job_rec_id-0.2

dfZZ <- events %>% filter(dtstart==dtstart & slurm_mode=='bZZ' & run_id==1)
dfZZ$job_rec_id2 <- dfZZ$job_rec_id+0.2

#print(cbind(df1 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs1=JobRecID, start1=StartTime), df2 %>% arrange(slurm_mode, dtstart, run_id,StartTime) %>% select(jobs2=JobRecID, start2=StartTime)))

df <- rbind(dfRR,dfZZ) %>% mutate(id=paste(slurm_mode,dtstart,run_id)) %>% arrange(run_id,t)
dfs <- filter(df, metric %in% c("submit_job","launch_job","job_epilog_complete")) %>% 
  dplyr::select(id,job_rec_id,job_rec_id2,metric,t) %>%
  group_by(id,job_rec_id,metric) %>%
  summarise(job_rec_id2=last(job_rec_id2),t=last(t))%>%
  spread(metric,t)


marker=list(size=10, line=list(width=2))
p <- plot_ly(df) %>%
    add_segments(data = filter(df, metric=='backfill'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("grey"),alpha=I(0.5), linetype=~id, name="backfiller start") %>%
    add_segments(data = filter(df, metric=='sched'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("#AED6F1"),alpha=I(0.5), linetype=~id, name="sched start") %>% #light blue
    add_segments(data = filter(df, metric=='job_time_limits_testing'), y=I(1000),yend=I(1501), x=~t,xend=~t,color=I("#AEF1D6"),alpha=I(0.5), linetype=~id, name="timelim check") %>% #light green
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~submit_job,xend=~launch_job,color=I("grey"), name="Wait Period") %>%
    add_segments(data = dfs, y=~job_rec_id2,yend=~job_rec_id2, x=~launch_job,xend=~job_epilog_complete,color=I("red"), name="Run Period") %>%
    add_markers(data = df %>% filter(metric=="submit_job"), y=~job_rec_id2, x=~t, color=I("grey"), symbol=I('o'), name="Submit Time",marker=marker) %>%
    add_markers(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2, x=~t, color=~value, colors=c("#0000FF","#00FF00"), symbol=I('cross'),marker=marker) %>% #I('+')
    add_markers(data = df %>% filter(metric=="job_epilog_complete"), y=~job_rec_id2, x=~t, color=I("red"), symbol=I('x'), name="End Time",marker=marker) %>%
    add_paths(data = df %>% filter(metric=="launch_job"), y=~job_rec_id2,x=~t, linetype=~id, legendgroup="Execution Order", color=I('black')) %>% 
    layout(
      yaxis = list(dtick = 1),
      xaxis = list(dtick = 10)
    )
#htmlwidgets::saveWidget(p, "sample_sched_didnt_start_after_1004_ends.html")
  #

  # ,legendgrouptitle=list(text="Execution Order"

#%>%
#  scale_y_continuous(breaks=seq(min(df$JobRecID),max(df$JobRecID),1)) + 
  #theme(panel.grid.minor = element_line(colour="black", size=0.5)) +
#  scale_x_continuous(breaks = seq(0, max(df2$EndTime), 5), minor_breaks = seq(0, max(df2$EndTime), 2)) 
#ggplotly(p)
p
```


```{r}
#sched
#backfill
#job_time_limits_testing
dftRR <- dfRR %>% arrange(t) %>% filter(t > 180) # %>% mutate(diff=t-lag(t))
dfRR
```
```{r}
#metric=="sched" & 
dftZZ <- dfZZ %>% arrange(t) %>% filter(t > 180) # %>% mutate(diff=t-lag(t))
dftZZ
```


```{r}
#sched
#backfill
#job_time_limits_testing
dftRR <- dfRR %>% arrange(t) %>% filter(metric=="job_time_limits_testing") %>% mutate(diff=t-lag(t))
dftRR
```

```{r}
#metric=="sched" & 
dftZZ <- dfZZ %>% arrange(t) %>% filter(metric=="job_time_limits_testing") %>% mutate(diff=t-lag(t))
dftZZ
#2022-01-01 00:00:11.998497
```

```{r}
df <- events %>% group_by(slurm_mode) %>% filter(metric=='_slurmctld_background_cycle') %>% mutate(dt=t-lag(t)-1) %>% filter(!is.na(dt))
#hist(df$dt) & dt>0.01
#df
ggplot(df, aes(x=log(dt), fill=slurm_mode)) +
  geom_histogram(position="dodge",bins=10)
```
```{r}

dft1 <- dft1 %>% mutate(t_zz=dft2$t[1:94],dt=t-t_zz)
dft1

```


```{r}
events %>% filter(metric=="slurm_start_time")
```

# Utilization
```
# 187G RAM
NodeName=DEFAULT RealMemory=187000 Sockets=2 CoresPerSocket=16 Weight=60
NodeName=n[001-087] Feature=CPU-Gold-6130,OPA
NodeName=gn[001-002] Gres=gpu:tesla_p100-pcie-16gb:2 Feature=CPU-Gold-6130,OPA,P100 Weight=190

# 187G RAM
NodeName=DEFAULT CPUs=40 RealMemory=187000 Sockets=2 CoresPerSocket=20 ThreadsPerCore=1
NodeName=g[001-008] Gres=gpu:tesla_v100-pcie-32gb:2 Feature=CPU-Gold-6230,IB,V100 Weight=190
NodeName=m[001-096] Feature=CPU-Gold-6230,IB Weight=70

# 754G RAM
NodeName=DEFAULT RealMemory=754000 Sockets=2 CoresPerSocket=20
NodeName=b[001-024] Feature=CPU-Gold-6230,IB Weight=160
```

```{r}
# Cores 
87*32+2*32+8*40+96*40+24*40

#nodes_names <- expand_slurm_hostlists(c("n[001-087]","gn[001-002]","g[001-008]","m[001-096]","b[001-024]"))
#nodes <- unlist(nodes)
node_desc <- list(
    list(
        Name="Nodes_N",
        Nodes=expand_hostlist("n[001-087]"),
        Procs=32
    ),
    list(
        Name="Nodes_GN",
        Nodes=expand_hostlist("gn[001-002]"),
        Procs=32
    ),
    list(
        Name="Nodes_G",
        Nodes=expand_hostlist("g[001-008]"),
        Procs=40
    ),
    list(
        Name="Nodes_M",
        Nodes=expand_hostlist("m[001-096]"),
        Procs=40
    ),
    list(
        Name="Nodes_B",
        Nodes=expand_hostlist("b[001-024]"),
        Procs=40
    )
)
names(nodes_desc) <- unique(sapply(nodes_desc,function(n){n$Name}))
```


```{r}
sacct0 <- read_sacct_out("/home/nikolays/slurm_sim_ws/slurm_model/ubhpc/results/bumblebee/workload/dtstart_55_1/slurm_acct.out", extract_node_list = TRUE)
util <- get_utilization(sacct0,7968-2*32,dt=60L)
mean(util$total_norm)
```
```{r}
dt <- as.integer(60)
    
nodes_names <- unlist(sapply(node_desc,function(x){x$Nodes}))
total_proc <- sum(unlist(sapply(node_desc,function(x){x$Procs*length(x$Nodes)})))
total_nodes <- length(nodes_names)

ts0 <- as.integer(min(unlist(sacct0[,c("Submit","Eligible","Start","End")]),na.rm = TRUE))
ts1 <- as.integer(max(unlist(sacct0[,c("Submit","Eligible","Start","End")]),na.rm = TRUE))


ts0 <- as.integer(ts0/dt-1L)*dt
ts1 <- as.integer(ts1/dt+2L)*dt

ts <- seq(ts0,ts1,dt)
t <- as.POSIXct(ts, origin="1970-01-01")
utilization <- data.frame(ts,t,matrix(data=0.0, ncol = length(nodes_names)+4, nrow = length(ts)))
colnames(utilization) <- c("ts","t",nodes_names,"total","total_norm","total_nodes","total_nodes_norm")

Njobs <- nrow(sacct0)
for(ijob in 1:Njobs){
    jts_0 <- as.integer(sacct0$Start[[ijob]])
    jts_1 <- as.integer(sacct0$End[[ijob]])
    
    iperiod0 <- as.integer((jts_0-ts0)/dt) + 1L
    iperiod01 <- iperiod0 + 1L
    iperiod10 <- as.integer((jts_1-ts0)/dt) + 1L
    iperiod1 <- iperiod10 + 1L
    nnodes <- length(sacct0$NodeListFull[[ijob]])
    ppn <- sacct0$NCPUS[[ijob]]/nnodes
    
    if(iperiod10>iperiod01){
        for(node in sacct0$NodeListFull[[ijob]]){
            utilization[[node]][iperiod01:(iperiod10-1L)] <- utilization[[node]][iperiod01:(iperiod10-1L)] + ppn
        }
    }
    
    if(iperiod10> iperiod0)
    {
        #i.e. two ends
        for(node in sacct0$NodeListFull[[ijob]]){
            utilization[[node]][iperiod0] <- utilization[[node]][iperiod0] + ((ts[iperiod01]-jts_0)/dt)*ppn
            utilization[[node]][iperiod10] <- utilization[[node]][iperiod10] + ((jts_1-ts[iperiod10])/dt)*ppn
        }
    }else{
        for(node in sacct0$NodeListFull[[ijob]]){
            utilization[[node]][iperiod0] <- utilization[[node]][iperiod0] + ((jts_1-jts_0)/dt)*ppn
        }
    }
}
utilization$total <- rowSums(utilization[,nodes_names])
utilization$total_norm <- utilization$total /total_proc
utilization$total_node <- rowSums(utilization[,nodes_names]>0)
utilization$total_node_norm <- utilization$total_node /total_nodes

mean(utilization$total_norm)
mean(utilization$total_node_norm)
#util_nodes <- get_utilization_old(sacct0,nodes_desc,dt=60L)
```
```{r}
mean(sacct0$WaitHours)
hist(sacct0$WaitHours,breaks=0:700)
```
```{r}
ggplot(utilization,aes(x=t,y=total_norm))+geom_line()
ggplot(utilization,aes(x=t,y=total_node_norm))+geom_line()

```


```{r}
ggplot(util,aes(x=t,y=total_norm))+geom_line()

```




