---
title: "UBHPC Virtual Cluster Simulation: Get Data"
author: nikolays
date: 1/11/22
output: html_notebook
---


```{r setup}
setwd(path.expand("~/slurm_sim_ws/slurm_model/ubhpc/analysis"))
library(stringr)
library(rjson)
library(dplyr)
library(lubridate)

#detach("package:RSlurmSimTools", unload=TRUE)
#devtools::document(path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"))
#devtools::install_local(path=path.expand("~/slurm_sim_ws/slurm_sim_tools/src/RSlurmSimTools"), force=TRUE)
library(RSlurmSimTools)


library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
#library(DepthProc)
reticulate::source_python(file.path(system.file("python", package = "RSlurmSimTools"),"hostlist.py"))
#library(gplots)
library(parallel)
```



```{r pressure, echo=FALSE}
#' read_sacct_out_clean - Read properly escaped \code{sacct} output, 
#' 
#' Read properly escaped \code{sacct} output, for non-escaped sacct 
#' output use \code{slurmsim sacctlog reformat} CLI command
#' 
#' @param filename file to read
#' @param run_id (optional) run_id column to set
#' @param config_id (optional) config_id column to set
#' @param dstart (optional) dstart column to set
#' @return data frame
#' 
read_sacct_out_clean <- function(filename,nodes_desc=NULL,extract_node_list=FALSE, run_id=NULL){
    #slurm_log <- read.table(filename, header = TRUE, sep = "|",as.is = TRUE)
    slurm_log <- data.table::fread(filename,sep="|",header=TRUE)
    
    #for(col in c("Submit","Eligible","Start","End","Elapsed","Timelimit",
    #             "Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        #cat(paste0(col,"S=",col,",\n"))
        #cat(paste0(col,"S,"))
    #}
    slurm_log <-  dplyr::rename(slurm_log,
        JobId=JobID,
        local_job_id=JobIDRaw,
        NodeCount=NNodes,
        SubmitS=Submit,
        EligibleS=Eligible,
        StartS=Start,
        EndS=End,
        ElapsedS=Elapsed,
        TimelimitS=Timelimit,
        ClusterS=Cluster,
        PartitionS=Partition,
        AccountS=Account,
        GroupS=Group,
        UserS=User,
        ExitCodeS=ExitCode,
        StateS=State,
        QOSS=QOS
    )
    
    #convert to proper format
    for(col in c("Submit","Eligible","Start","End")){
        slurm_log[[paste0(col,"Time")]] <- as.POSIXct(slurm_log[[paste0(col,"S")]],format = "%Y-%m-%dT%H:%M:%S", origin = '1970-01-01')
    }
    
    #duration
    for(col in c("Elapsed","Timelimit")){
        slurm_log[,col] <- extract_slurm_period(slurm_log[[paste0(col,"S")]])
    }
    
    #factor
    for(col in c("Cluster","Partition","Account","Group","User", "ExitCode","State","QOS")){
        slurm_log[,col] <- factor(slurm_log[[paste0(col,"S")]])
    }
    
    #state
    slurm_log$StateS <- as.character(slurm_log$StateS)
    slurm_log$StateS[grepl("CANCELLED",slurm_log$StateS)] <- "CANCELLED"
    slurm_log$State <- as.factor(slurm_log$StateS)
    
    #extract node list
    if(extract_node_list==TRUE){
        #python.load(file.path(rutil_dir,"..","src","hostlist.py"))
        #slurm_log$NodeListFull <- python.call("expand_hostlists_to_str",slurm_log$NodeList)
        slurm_log$NodeListFull <- expand_hostlists_to_list(slurm_log$NodeList)
    }

    #convert memory
    slurm_log$ReqMem[slurm_log$ReqMem=="0n"] <- "0Mn"
    reqmem <- stringr::str_match_all(slurm_log$ReqMem, "([\\.0-9]+)([MG])([nc]?)")
    
    reqmem_size <- sapply(reqmem,function(r){
        as.integer(r[[2]])
    })
    reqmem_unit <- sapply(reqmem,function(r)r[[3]])
    reqmem_perwhat <- sapply(reqmem,function(r)r[[4]])
    #convert to MB
    reqmem_size[reqmem_unit=="G"] <- reqmem_size[reqmem_unit=="G"]*1024
    
    slurm_log$ReqMemSize <- reqmem_size
    slurm_log$ReqMemPerNode <- reqmem_perwhat=="n" || reqmem_perwhat==""
    
    slurm_log$ReqMem <- NULL
    
    #set proper NA
    #slurm_log$ReqGRES[slurm_log$ReqGRES==""] <- NA
    if(!is.null(nodes_desc)){
      nr <- max(sapply(nodes_desc,function(n){length(n$Nodes)}))
      
      nodes_mat <- sapply(nodes_desc,function(n){c(n$Nodes,rep(NA,nr-length(n$Nodes)))})
      
      #assing nodes
      nodes_types_used <- sapply(slurm_log$NodeListFull,function(nodes){
        apply(nodes_mat,2,function(v){length(intersect(v,nodes))})
      })
      
      slurm_log <- cbind(slurm_log,t(nodes_types_used))
    }
      
    slurm_log$SubmitTS <- as.integer(slurm_log$SubmitTime)
    slurm_log$StartTS <- as.integer(slurm_log$StartTime)
    slurm_log$EndTS <- as.integer(slurm_log$EndTime)
    
    mintime <- as.POSIXct(min(slurm_log$SubmitTS,na.rm = TRUE), origin = '1970-01-01')
    
    slurm_log$SubmitTS <- as.integer(slurm_log$SubmitTime)
    slurm_log$StartTS <- as.integer(slurm_log$StartTime)
    slurm_log$EndTS <- as.integer(slurm_log$EndTime)
    
    slurm_log$Submit <- slurm_log$SubmitTime - mintime
    slurm_log$Start <- slurm_log$StartTime - mintime
    slurm_log$End <- slurm_log$EndTime - mintime
    
    
    slurm_log$WaitHours <- as.integer(slurm_log$StartTime-slurm_log$SubmitTime)/3600.0
    slurm_log$WaitHours[slurm_log$WaitHours<0.0] <- 0
    #slurm_log$WaitHours[slurm_log$WaitHours<0.0] <- slurm_log$WaitHours[slurm_log$WaitHours<0.0]+1
    
    slurm_log$WallHours <- as.integer(slurm_log$Elapsed)/3600.0
    slurm_log$NodeHours <- slurm_log$WallHours*slurm_log$NodeCount
    
    #shift 0 value for log scales
    slurm_log$WaitHours4log <- slurm_log$WaitHours
    slurm_log$WaitHours4log[slurm_log$WaitHours4log<1/60]<-1/60
    #shift 0 value for log scales
    slurm_log$WallHours4log <- slurm_log$WallHours
    slurm_log$WallHours4log[slurm_log$WallHours4log<1/60]<-1/60
    
    slurm_log$run_id <- run_id
    
    slurm_log <- dplyr::arrange(slurm_log,SubmitTS)%>%
        dplyr::select(-c(SubmitS,EligibleS,StartS,EndS,ElapsedS,TimelimitS,ClusterS,
                         PartitionS,AccountS,GroupS,UserS,ExitCodeS,StateS,QOSS))
    return(slurm_log)
}

jobs <- rbind(
  read_sacct_out_clean("zstdcat ../../../slurm_model_archive/ubhpc/vc_sim_1/slurm_acct.out.zst", run_id = 1),
  read_sacct_out_clean("zstdcat ../../../slurm_model_archive/ubhpc/vc_sim_2/slurm_acct.out.zst", run_id = 2),
  read_sacct_out_clean("zstdcat ../../../slurm_model_archive/ubhpc/vc_sim_3/slurm_acct.out.zst", run_id = 3),
  read_sacct_out_clean("zstdcat ../../../slurm_model_archive/ubhpc/vc_sim_4/slurm_acct.out.zst", run_id = 4)
)

jobs$job <- as.integer(stringr::str_replace(jobs$JobName, "job_",""))
```

```{r}
start_times <- jobs %>% group_by(job) %>% 
  summarise(
    submit=mean(Submit)/3600,
    submit_sd=sd(Submit)/3600,
    start=mean(Start)/3600,
    start_sd=sd(Start)/3600,
    waithours=mean(Start-Submit)/3600,
    waithours_sd=sd(Start-Submit)/3600,
    )
```

```{r}
ggplot(start_times, aes(x=start_sd)) + geom_histogram()
```
```{r}
ggplot(start_times, aes(x=waithours )) + geom_histogram()
```
```{r}
cat(
  mean(start_times$waithours),"\n",
  mean(start_times$waithours_sd),"\n")
```

```{r}
mean(jobs$WaitHours)
```