version: "3.8"
services:
    headnode:
        image: nsimakov/slurm_vc:slurm-20.02-sim
        hostname: headnode
        shm_size: 64M
        command: ["sshd", "munged", "mysqld", "/opt/cluster/ubhpc/utils/start_head_node.sh", "-loop"]
        networks:
            network1:
              ipv4_address: 172.32.3.11
        volumes:
        - './results:/root/results'
        - './etc:/opt/cluster/ubhpc/etc'
        - './utils:/opt/cluster/ubhpc/utils'
        - './job_traces:/opt/cluster/ubhpc/job_traces'
    compute-1:
        image: nsimakov/slurm_vc:slurm-20.02-sim
        hostname: compute-1
        command: ["sshd", "munged", "/opt/cluster/ubhpc/utils/start_compute_node.sh", "-loop"]
        networks:
            network1:
              ipv4_address: 172.32.3.21
        volumes:
        - './results:/root/results'
        - './etc:/opt/cluster/ubhpc/etc'
        - './utils:/opt/cluster/ubhpc/utils'
        - './job_traces:/opt/cluster/ubhpc/job_traces'
    compute-2:
        image: nsimakov/slurm_vc:slurm-20.02-sim
        hostname: compute-2
        command: ["sshd", "munged", "/opt/cluster/ubhpc/utils/start_compute_node.sh", "-loop"]
        networks:
            network1:
              ipv4_address: 172.32.3.22
        volumes:
        - './results:/root/results'
        - './etc:/opt/cluster/ubhpc/etc'
        - './utils:/opt/cluster/ubhpc/utils'
        - './job_traces:/opt/cluster/ubhpc/job_traces'

    
networks:
    network1:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.32.3.0/24"
