#!/usr/bin/env bash

if [[ "`hostname -s`" == "head-node" ]]; then
    sleep 5
    # add/modify QOS
    sacctmgr  -i modify QOS set normal Priority=0
    sacctmgr  -i add QOS Name=supporters Priority=100
    # add cluster
    sacctmgr -i add cluster Name=micro Fairshare=1 QOS=normal,supporters
    # add accounts
    sacctmgr -i add account name=account0 Fairshare=100
    sacctmgr -i add account name=account1 Fairshare=100
    sacctmgr -i add account name=account2 Fairshare=100
    # add admin
    sacctmgr -i add user name=admin DefaultAccount=account0 MaxSubmitJobs=1000 AdminLevel=Administrator
    # add users
    sacctmgr -i add user name=user1 DefaultAccount=account1 MaxSubmitJobs=100000
    sacctmgr -i add user name=user2 DefaultAccount=account1 MaxSubmitJobs=1000
    sacctmgr -i add user name=user3 DefaultAccount=account1 MaxSubmitJobs=1000
    sacctmgr -i add user name=user4 DefaultAccount=account2 MaxSubmitJobs=1000
    sacctmgr -i add user name=user5 DefaultAccount=account2 MaxSubmitJobs=1000
    # add users to qos level
    sacctmgr -i modify user set qoslevel="normal,supporters"

    # check results
    sacctmgr list associations format=Account,Cluster,User,Fairshare tree withd
fi
