#!/usr/bin/env bash

echo "Adding nodes to /etc/hosts"
cp /etc/hosts /etc/hosts.old
grep -v `hostname -s` /etc/hosts.old > /etc/hosts
rm /etc/hosts.old
echo "head-node 172.31.0.1" >> /etc/hosts
echo "compute000 172.31.0.100" >> /etc/hosts

# clean profiles
if [[ -d "/scratch/acct_gather" ]]; then
    rm -rf /scratch/acct_gather/*
fi

echo "Creating local user system accounts"
if [[ "`hostname -s`" == "head-node" ]]; then
    USERADD_FLAGS="-m"
else
    USERADD_FLAGS="-M"
fi

useradd $USERADD_FLAGS -s /bin/bash admin && \
echo 'admin:admin' |chpasswd && \
usermod -a -G wheel admin && \
echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
useradd $USERADD_FLAGS -s /bin/bash user1 && \
echo 'user1:user' |chpasswd && \
useradd $USERADD_FLAGS -s /bin/bash user2 && \
echo 'user2:user' |chpasswd && \
useradd $USERADD_FLAGS -s /bin/bash user3 && \
echo 'user3:user' |chpasswd && \
useradd $USERADD_FLAGS -s /bin/bash user4 && \
echo 'user4:user' |chpasswd && \
useradd $USERADD_FLAGS -s /bin/bash user5 && \
echo 'user5:user' |chpasswd

# lets populate history with frequent commands
if [[ "`hostname -s`" == "head-node" ]]; then
cat > /root/.bash_history << EOF
tail -f /var/log/slurm/slurmctld.log
cat /var/log/slurm/slurmctld.log
sacctmgr list associations format=Account,Cluster,User,Fairshare tree withd
scontrol show assoc
su - user1 -c "sbatch -p normal -q normal -A account1 -N 1 -n 8 --mem=1000M -t 5:00 /usr/local/miniapps/mulmat.job 512 30 1 30 30"
su - user1 -c "sbatch -p normal -q normal -A account1 -N 2 -n 16 --mem=1000M -t 5:00 /usr/local/miniapps/mulmat.job 512 30 1 30 30"
watch squeue
squeue
sinfo
EOF
else
cat > /root/.bash_history << EOF
cmd_start /vctools/init_system munged slurmd sshd
tail -f /var/log/slurm/slurmd.log
cat /var/log/slurm/slurmd.log
EOF
fi

# for debugging
#yum install -y gdb-gdbserver gdb
