---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(lubridate)
```


# Load fdata
```{r}
getwd()
setwd("/Users/yuqinglin/PycharmProjects/slurm_model/apps/")
slt = read.table('simulation/job_traces/nano_job_traces.log',sep="|")
colnames(slt)=c("jobid","jobidraw","cluster","partition","account","group","gid","user","uid",
                "submit","eligible","start","end","elapsed","exitcode","state","nnodes","ncpus","reqcpus","reqmem","reqgres","reqtres","timelimit","nodelist","jobname")

slt$submit <- as.POSIXct(as.character(slt$submit), format="%Y-%m-%dT%H:%M:%S")
slt$start <- as.POSIXct(as.character(slt$start), format="%Y-%m-%dT%H:%M:%S")
slt$end  <- as.POSIXct(as.character(slt$end), format="%Y-%m-%dT%H:%M:%S")
slt$walltime <- as.numeric(slt$end - slt$start);
slt$submitUnixTime <- as.numeric(slt$submit)
slt
```

```{r}
#jobs_by_hour <- slt %>% filter(start >= as.POSIXct("2020-05-25 00:00:00") & start < as.POSIXct("2020-05-27 00:00:00")) %>%
  #group_by(start_hour=floor_date(start, unit="5 mins")) %>%
  #summarise(n=n(),cpu_hours=sum(ncpus*walltime/3600)) %>% ungroup()

#ggplot(jobs_by_hour,aes(start_hour,n))+geom_point()
#ggplot(jobs_by_hour,aes(start_hour,cpu_hours))+geom_point()

```

```{r}
write.csv(slt,file='/Users/yuqinglin/PycharmProjects/slurm_model/nano/job_traces.csv')
 # write.csv(slt,file='//Users/yuqinglin/Desktop/rOut/slurm_log.csv')
```

